# Introduction to Numpy

In [1]:
import sys
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
b = np.array([0,.5,1,1.5,2])

In [4]:
# Everything works the same way as with python list such ad indexing and slicing
a[0]

1

In [5]:
a[1:3]

array([2, 3])

In [6]:
# Only one difference or advantage is that we can pass a list of indices to the array
# it will result in a new numpy array with the elements corresponding to the indices

b[[0,2,-1]]

array([0., 1., 2.])

In [7]:
# Use dtype to determine the data type of the array

a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('float64')

In [9]:
# We can also specify the data type of the array when creating it

np.array([1,2,3,4], dtype = float)

array([1., 2., 3., 4.])

In [10]:
np.array([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

## Dimensions and shapes

In [11]:
# numpy can be used to crate multi-dimensional arrays

c = np.array([
    [1,2,3],
    [4,5,6]
])

In [12]:
# We can use the shape attribute to determine the shape of the array

c.shape

(2, 3)

In [13]:
# use ndim to determine the number of dimensions

c.ndim

2

In [14]:
# use size to determine the number of elements in the array

c.size

6

In [15]:
# let's create a 3 dimensional array

d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [16]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
d.shape

(2, 2, 3)

In [18]:
d.ndim

3

In [19]:
d.size

12

- Be careful when creating arrays with different dimensions
- Irregular arrays will result in a wrong shape or output

In [20]:
# indexing and slicing multi-dimensional arrays

A = np.array([
#    0 1 2
    [1,2,3], # 0
    [4,5,6], # 1
    [7,8,9]  # 2
])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
A[1]

array([4, 5, 6])

In [22]:
A[1][0]

4

In [23]:
# other way to index multi-dimensional arrays
# is to pass a list of indices
# in this case the list of indices corresponds to the dimensions of the array
# for example, if we want to get the element 6, we need to pass the indices [1,2]
# Hence, A[1,2] i.e. row 1, column 2
# Code: A[d1,d2,d3,...,dn]

A[1,2]

6

In [24]:
# slicing multi-dimensional arrays

A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [25]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [26]:
A[:2, 1:]

array([[2, 3],
       [5, 6]])

In [27]:
# assigning values to multi-dimensional arrays

A[1] = np.array([10,10,10])

A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

## Built ins

In [28]:
a = np.array([1,2,3,4])

In [29]:
a.sum()

10

In [30]:
a.mean()

2.5

In [31]:
a.std()

1.118033988749895

In [32]:
a.var()

1.25

In [33]:
# Same thing can be done with multi-dimensional arrays

A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
A.sum()

45

In [35]:
A.mean()

5.0

In [36]:
# Or we can specify the axis along which we want to perform the operation

A.sum(axis = 0)

array([12, 15, 18])

In [37]:
A.sum(axis = 1)

array([ 6, 15, 24])